protected/models/Vuelos.php
<?php

Yii::import('application.models._base.BaseVuelos');

class Vuelos extends BaseVuelos
{
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}
}

protected/controllers/BoletosController.php
<?php

class BoletosController extends GxController {

public function filters() {
	return array(
			'accessControl', 
			);
}

public function accessRules() {
	return array(
			array('allow', 
				'actions'=>array('index', 'view'),
				'users'=>array(Yii::app()->user->id),
				),
			array('allow', 
				'actions'=>array('minicreate', 'create', 'update', 'admin', 'delete'),
				'users'=>array(Yii::app()->user->id),
				),
			array('deny', 
				'users'=>array('*'),
				),
			);
}

	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Boletos'),
		));
	}

	public function actionCreate() {
		$model = new Boletos;

		$this->performAjaxValidation($model, 'boletos-form');

		if (isset($_POST['Boletos'])) {
			$model->setAttributes($_POST['Boletos']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->idboleto));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Boletos');

		$this->performAjaxValidation($model, 'boletos-form');

		if (isset($_POST['Boletos'])) {
			$model->setAttributes($_POST['Boletos']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->idboleto));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Boletos')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Su solicitud es inválida.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Boletos');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
		$model = new Boletos('search');
		$model->unsetAttributes();

		if (isset($_GET['Boletos']))
			$model->setAttributes($_GET['Boletos']);

		$this->render('admin', array(
			'model' => $model,
		));
	}

}

protected/controllers/ClasesController.php
<?php

class ClasesController extends GxController {

public function filters() {
	return array(
			'accessControl', 
			);
}

public function accessRules() {
	return array(
			array('allow', 
				'actions'=>array('index', 'view'),
				'users'=>array('@'),
				),
			array('allow', 
				'actions'=>array('minicreate', 'create', 'update', 'admin', 'delete'),
				'users'=>array(Yii::app()->user->id),
				),
			array('deny', 
				'users'=>array('*'),
				),
			);
}

	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Clases'),
		));
	}

	public function actionCreate() {
		$model = new Clases;

		$this->performAjaxValidation($model, 'clases-form');

		if (isset($_POST['Clases'])) {
			$model->setAttributes($_POST['Clases']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->idclase));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Clases');

		$this->performAjaxValidation($model, 'clases-form');

		if (isset($_POST['Clases'])) {
			$model->setAttributes($_POST['Clases']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->idclase));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Clases')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Su solicitud es inválida.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Clases');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
		$model = new Clases('search');
		$model->unsetAttributes();

		if (isset($_GET['Clases']))
			$model->setAttributes($_GET['Clases']);

		$this->render('admin', array(
			'model' => $model,
		));
	}

}

protected/controllers/DestinosController.php
<?php

class DestinosController extends GxController {

public function filters() {
	return array(
			'accessControl', 
			);
}

public function accessRules() {
	return array(
			array('allow', 
				'actions'=>array('index', 'view'),
				'users'=>array(Yii::app()->user->id),
				),
			array('allow', 
				'actions'=>array('minicreate', 'create', 'update', 'admin', 'delete'),
				'users'=>array(Yii::app()->user->id),
				),
			array('deny', 
				'users'=>array('*'),
				),
			);
}

	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Destinos'),
		));
	}

	public function actionCreate() {
		$model = new Destinos;

		$this->performAjaxValidation($model, 'destinos-form');

		if (isset($_POST['Destinos'])) {
			$model->setAttributes($_POST['Destinos']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->iddestino));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Destinos');

		$this->performAjaxValidation($model, 'destinos-form');

		if (isset($_POST['Destinos'])) {
			$model->setAttributes($_POST['Destinos']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->iddestino));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Destinos')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Su solicitud es inválida.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Destinos');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
		$model = new Destinos('search');
		$model->unsetAttributes();

		if (isset($_GET['Destinos']))
			$model->setAttributes($_GET['Destinos']);

		$this->render('admin', array(
			'model' => $model,
		));
	}

}

protected/controllers/OrigenesController.php
<?php

class OrigenesController extends GxController {

public function filters() {
	return array(
			'accessControl', 
			);
}

public function accessRules() {
	return array(
			array('allow', 
				'actions'=>array('index', 'view'),
				'users'=>array(Yii::app()->user->id),
				),
			array('allow', 
				'actions'=>array('minicreate', 'create', 'update', 'admin', 'delete'),
				'users'=>array(Yii::app()->user->id),
				),
			array('deny', 
				'users'=>array('*'),
				),
			);
}

	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Origenes'),
		));
	}

	public function actionCreate() {
		$model = new Origenes;

		$this->performAjaxValidation($model, 'origenes-form');

		if (isset($_POST['Origenes'])) {
			$model->setAttributes($_POST['Origenes']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->idorigen));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Origenes');

		$this->performAjaxValidation($model, 'origenes-form');

		if (isset($_POST['Origenes'])) {
			$model->setAttributes($_POST['Origenes']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->idorigen));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Origenes')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Su solicitud es inválida.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Origenes');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
		$model = new Origenes('search');
		$model->unsetAttributes();

		if (isset($_GET['Origenes']))
			$model->setAttributes($_GET['Origenes']);

		$this->render('admin', array(
			'model' => $model,
		));
	}

}

protected/controllers/VuelosController.php
<?php

class VuelosController extends GxController {

	public function filters() {
		return array(
				'accessControl', 
				);
	}

	public function accessRules() {
		return array(
				array('allow',
					'actions'=>array('index','view'),
					'users'=>array('*'),
					),
				array('allow', 
					'actions'=>array('minicreate', 'create','update'),
					'users'=>array(Yii::app()->user->id),
					),
				array('allow', 
					'actions'=>array('admin','delete'),
					'users'=>array(Yii::app()->user->id),
					),
				array('deny', 
					'users'=>array('*'),
					),
				);
	}
	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Vuelos'),
		));
	}

	public function actionCreate() {
		$model = new Vuelos;

		$this->performAjaxValidation($model, 'vuelos-form');

		if (isset($_POST['Vuelos'])) {
			$model->setAttributes($_POST['Vuelos']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->idvuelo));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Vuelos');

		$this->performAjaxValidation($model, 'vuelos-form');

		if (isset($_POST['Vuelos'])) {
			$model->setAttributes($_POST['Vuelos']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->idvuelo));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Vuelos')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Vuelos');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
		$model = new Vuelos('search');
		$model->unsetAttributes();

		if (isset($_GET['Vuelos']))
			$model->setAttributes($_GET['Vuelos']);

		$this->render('admin', array(
			'model' => $model,
		));
	}

}

protected/views/vuelos/_form.php
<div class="form">


<?php $form = $this->beginWidget('GxActiveForm', array(
	'id' => 'vuelos-form',
	'enableAjaxValidation' => true,
));
?>

	<p class="note">
		<?php echo Yii::t('app', 'Campos con'); ?> <span class="required">*</span> <?php echo Yii::t('app', 'son requeridos'); ?>.
	</p>

	<?php echo $form->errorSummary($model); ?>
<div style="padding-left:30px;">
		<div class="row">
		<?php echo $form->labelEx($model,'idaerolinea'); ?>
		<?php echo $form->dropDownList($model, 'idaerolinea', GxHtml::listDataEx(Aerolineas::model()->findAllAttributes(null, true))); ?>
		<?php echo $form->error($model,'idaerolinea'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'hora'); ?>
		<?php echo $form->textField($model, 'hora'); ?>
		<?php echo $form->error($model,'hora'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'idorigen'); ?>
		<?php echo $form->dropDownList($model, 'idorigen', GxHtml::listDataEx(Origenes::model()->findAllAttributes(null, true))); ?>
		<?php echo $form->error($model,'idorigen'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'iddestino'); ?>
		<?php echo $form->dropDownList($model, 'iddestino', GxHtml::listDataEx(Destinos::model()->findAllAttributes(null, true))); ?>
		<?php echo $form->error($model,'iddestino'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'idclase'); ?>
		<?php echo $form->dropDownList($model, 'idclase', GxHtml::listDataEx(Clases::model()->findAllAttributes(null, true))); ?>
		<?php echo $form->error($model,'idclase'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'costo'); ?>
		<?php echo $form->textField($model, 'costo'); ?>
		<?php echo $form->error($model,'costo'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'maxboleto'); ?>
		<?php echo $form->textField($model, 'maxboleto'); ?>
		<?php echo $form->error($model,'maxboleto'); ?>
		</div><!-- row -->
</div>
		
<?php
echo GxHtml::submitButton(Yii::t('app', 'Guardar'));
$this->endWidget();
?>
</div>
</div><!-- form -->

protected/views/vuelos/_search.php
<div class="wide form">

<?php $form = $this->beginWidget('GxActiveForm', array(
	'action' => Yii::app()->createUrl($this->route),
	'method' => 'get',
)); ?>
<div style="padding-left:30px;">
	<div class="row">
		<?php echo $form->label($model, 'idvuelo'); ?>
		<?php echo $form->textField($model, 'idvuelo'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'idaerolinea'); ?>
		<?php echo $form->dropDownList($model, 'idaerolinea', GxHtml::listDataEx(Aerolineas::model()->findAllAttributes(null, true)), array('prompt' => Yii::t('app', 'All'))); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'hora'); ?>
		<?php echo $form->textField($model, 'hora'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'idorigen'); ?>
		<?php echo $form->dropDownList($model, 'idorigen', GxHtml::listDataEx(Origenes::model()->findAllAttributes(null, true)), array('prompt' => Yii::t('app', 'All'))); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'iddestino'); ?>
		<?php echo $form->dropDownList($model, 'iddestino', GxHtml::listDataEx(Destinos::model()->findAllAttributes(null, true)), array('prompt' => Yii::t('app', 'All'))); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'idclase'); ?>
		<?php echo $form->dropDownList($model, 'idclase', GxHtml::listDataEx(Clases::model()->findAllAttributes(null, true)), array('prompt' => Yii::t('app', 'All'))); ?>
	</div>
	<div class="row">
		<?php echo $form->label($model, 'costo'); ?>
		<?php echo $form->textField($model, 'costo'); ?>
	</div>
	<div class="row">
		<?php echo $form->label($model, 'maxboleto'); ?>
		<?php echo $form->textField($model, 'maxboleto'); ?>
	</div>

	<div class="row buttons">
		<?php echo GxHtml::submitButton(Yii::t('app', 'Buscar')); ?>
	</div>
</div>

<?php $this->endWidget(); ?>
</div>
</div><!-- search-form -->

protected/views/vuelos/_view.php
<div class="view">

	<?php echo GxHtml::encode($data->getAttributeLabel('idvuelo')); ?>:
	<?php echo GxHtml::link(GxHtml::encode($data->idvuelo), array('view', 'id' => $data->idvuelo)); ?>
	<br />

	<?php echo GxHtml::encode($data->getAttributeLabel('idaerolinea')); ?>:
		<?php echo GxHtml::encode(GxHtml::valueEx($data->idaerolinea0)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('hora')); ?>:
	<?php echo GxHtml::encode($data->hora); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('idorigen')); ?>:
		<?php echo GxHtml::encode(GxHtml::valueEx($data->idorigen0)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('iddestino')); ?>:
		<?php echo GxHtml::encode(GxHtml::valueEx($data->iddestino0)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('idclase')); ?>:
		<?php echo GxHtml::encode(GxHtml::valueEx($data->idclase0)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('costo')); ?>:
	<?php echo GxHtml::encode($data->costo); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('maxboleto')); ?>:
	<?php echo GxHtml::encode($data->maxboleto); ?>
	<br />

</div>

protected/views/vuelos/admin.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	Yii::t('app', 'Gestionar'),
);

$this->menu = array(
		array('label'=>Yii::t('app', 'Lista') . ' ' . $model->label(2), 'url'=>array('index')),
		array('label'=>Yii::t('app', 'Crear') . ' ' . $model->label(), 'url'=>array('create')),
	);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('vuelos-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1><?php echo Yii::t('app', 'Gestionar') . ' ' . GxHtml::encode($model->label(2)); ?></h1>

<p>
También puede escribir un operador de comparación(&lt;, &lt;=, &gt;, &gt;=, &lt;&gt; or =) o al principio de cada uno de los valores de búsqueda para especificar cómo se debe hacer la comparación..
</p>

<?php echo GxHtml::link(Yii::t('app', 'Advanced Search'), '#', array('class' => 'search-button')); ?>
<div class="search-form">
<?php $this->renderPartial('_search', array(
	'model' => $model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id' => 'vuelos-grid',
	'dataProvider' => $model->search(),
	'filter' => $model,
	'columns' => array(
		'idvuelo',
		array(
				'name'=>'idaerolinea',
				'value'=>'GxHtml::valueEx($data->idaerolinea0)',
				'filter'=>GxHtml::listDataEx(Aerolineas::model()->findAllAttributes(null, true)),
				),
		'hora',
		array(
				'name'=>'idorigen',
				'value'=>'GxHtml::valueEx($data->idorigen0)',
				'filter'=>GxHtml::listDataEx(Origenes::model()->findAllAttributes(null, true)),
				),
		array(
				'name'=>'iddestino',
				'value'=>'GxHtml::valueEx($data->iddestino0)',
				'filter'=>GxHtml::listDataEx(Destinos::model()->findAllAttributes(null, true)),
				),
		array(
				'name'=>'idclase',
				'value'=>'GxHtml::valueEx($data->idclase0)',
				'filter'=>GxHtml::listDataEx(Clases::model()->findAllAttributes(null, true)),
				),
		/*
		'maxboleto',
		*/
		array(
			'class' => 'CButtonColumn',
		),
	),
)); ?>

protected/views/vuelos/create.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	Yii::t('app', 'Crear'),
);

$this->menu = array(
	array('label'=>Yii::t('app', 'Lista') . ' ' . $model->label(2), 'url' => array('index')),
	array('label'=>Yii::t('app', 'Gestionar') . ' ' . $model->label(2), 'url' => array('admin')),
);
?>

<h1><?php echo Yii::t('app', 'Crear') . ' ' . GxHtml::encode($model->label()); ?></h1>

<?php
$this->renderPartial('_form', array(
		'model' => $model,
		'buttons' => 'create'));
?>

protected/views/vuelos/index.php
<?php

$this->breadcrumbs = array(
	Vuelos::label(2),
	Yii::t('app', 'Index'),
);

$this->menu = array(
    array('label'=>Yii::t('app', 'Crea') . ' ' . Compra::label(), 'url' => array('create')),
    array('label'=>Yii::t('app', 'Gestionar') . ' ' . Compra::label(2), 'url' => array('admin')),
);
?>

<h1><?php echo GxHtml::encode(Vuelos::label(2)); ?></h1>


<?php 
/*$this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
));*/
 $this->widget('zii.widgets.grid.CGridView', array(
    'dataProvider'=>$dataProvider,
    'columns'=>array(
        'idvuelo',
        'idaerolinea0',
        'idorigen0',
        'iddestino0',
        'hora',
        'idclase0',
        'costo',
    ),
 ));
?>

protected/views/vuelos/update.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	GxHtml::valueEx($model) => array('view', 'id' => GxActiveRecord::extractPkValue($model, true)),
	Yii::t('app', 'Update'),
);

$this->menu = array(

	array('label' => Yii::t('app', 'Lista') . ' ' . $model->label(2), 'url'=>array('index')),
	array('label' => Yii::t('app', 'Crear') . ' ' . $model->label(), 'url'=>array('create')),
	array('label' => Yii::t('app', 'Ver') . ' ' . $model->label(), 'url'=>array('view', 'id' => GxActiveRecord::extractPkValue($model, true))),
	array('label' => Yii::t('app', 'Gestionar') . ' ' . $model->label(2), 'url'=>array('admin')),	
);
?>

<h1><?php echo Yii::t('app', 'Actualizar') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>

<?php
$this->renderPartial('_form', array(
		'model' => $model));
?>

protected/views/vuelos/view.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	GxHtml::valueEx($model),
);

$this->menu=array(
	array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('index')),
	array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('create')),
	array('label'=>Yii::t('app', 'Update') . ' ' . $model->label(), 'url'=>array('update', 'id' => $model->idvuelo)),
	array('label'=>Yii::t('app', 'Delete') . ' ' . $model->label(), 'url'=>'#', 'linkOptions' => array('submit' => array('delete', 'id' => $model->idvuelo), 'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url'=>array('admin')),
);
?>

<h1><?php echo Yii::t('app', 'View') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data' => $model,
	'attributes' => array(
'idvuelo',
array(
			'name' => 'idaerolinea0',
			'type' => 'raw',
			'value' => $model->idaerolinea0 !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->idaerolinea0)), array('aerolineas/view', 'id' => GxActiveRecord::extractPkValue($model->idaerolinea0, true))) : null,
			),
'hora',
array(
			'name' => 'idorigen0',
			'type' => 'raw',
			'value' => $model->idorigen0 !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->idorigen0)), array('origenes/view', 'id' => GxActiveRecord::extractPkValue($model->idorigen0, true))) : null,
			),
array(
			'name' => 'iddestino0',
			'type' => 'raw',
			'value' => $model->iddestino0 !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->iddestino0)), array('destinos/view', 'id' => GxActiveRecord::extractPkValue($model->iddestino0, true))) : null,
			),
array(
			'name' => 'idclase0',
			'type' => 'raw',
			'value' => $model->idclase0 !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->idclase0)), array('clases/view', 'id' => GxActiveRecord::extractPkValue($model->idclase0, true))) : null,
			),
'maxboleto',
	),
)); ?>

<h2><?php echo GxHtml::encode($model->getRelationLabel('boletoses')); ?></h2>
<?php
	echo GxHtml::openTag('ul');
	foreach($model->boletoses as $relatedModel) {
		echo GxHtml::openTag('li');
		echo GxHtml::link(GxHtml::encode(GxHtml::valueEx($relatedModel)), array('boletos/view', 'id' => GxActiveRecord::extractPkValue($relatedModel, true)));
		echo GxHtml::closeTag('li');
	}
	echo GxHtml::closeTag('ul');
?>